household_power_consumption=read.table("household_power_consumption.txt", sep=";",header=T, stringsAsFactors = F)
household_power_consumption$Date=as.POSIXct(household_power_consumption$Date,format="%d/%m/%Y")
household_power_consumption<-subset(household_power_consumption,Date >= "2007-02-01" & Date <= "2007-02-02")
numeric_vars=c("Global_active_power", "Global_reactive_power","Voltage", "Global_intensity", "Sub_metering_1","Sub_metering_2","Sub_metering_3")
household_power_consumption[numeric_vars]=sapply(household_power_consumption[numeric_vars], as.numeric)
household_power_consumption$datetime=apply(household_power_consumption[c("Date", "Time")], 1,function(x){paste(x,collapse=" ")})
household_power_consumption$datetime=as.POSIXct(household_power_consumption$datetime, format="%Y-%m-%d %H:%M:%S")
png("plot2.png",width = 480, height=480)
plot(Global_active_power~datetime,data = household_power_consumption, type="l",xaxt="n",ylab="Global Active Power (kilowatts)", xlab="")
axis(1,at=as.POSIXct(c("2007-02-01 00:00:00", "2007-02-02 00:00:00", "2007-02-03 00:00:00")), labels = c("Thu", "Fri", "Sat"))
dev.off()
